FROM golang:1.24.8-alpine AS build
RUN apk add --no-cache ca-certificates git
RUN GOBIN=/out go install github.com/minio/minio@RELEASE.2025-10-15T17-29-55Z

FROM alpine:3.22
RUN apk add --no-cache ca-certificates && addgroup -S minio && adduser -S -G minio minio
COPY --from=build /out/minio /usr/local/bin/minio
USER minio
ENTRYPOINT ["/usr/local/bin/minio"]
